import { createDemoExportController } from '../../platform/export/demo-export.js';
import { createFileSessionController } from '../../platform/session/file-session.js';
import { createGlobalBindingsController } from '../../platform/global-bindings.js';
import { createShellController } from '../../ui/shell-controller.js';
import { createInstantiationControlsDialogController } from '../../ui/instantiation-controls-dialog.js';
import { createRenderSurfaceController } from '../../platform/render-surface/controller.js';
import { createInstallCounterController } from '../../platform/install-counter/controller.js';
import { createDefaultRivAppController } from '../../platform/default-riv-app/controller.js';

export function createPlatformStack({
    elements,
    callbacks,
} = {}) {
    const {
        applyCodeAndReload,
        applyStoredRuntimeVersionForCurrentFile,
        buildFileRuntimePreferenceId,
        captureVmControlSnapshot,
        cleanupInstance,
        consoleModeController,
        createDemoBundle,
        ensureEditorReady,
        ensureRuntime,
        ensureTauriBridge,
        eventLogController,
        getArtboardStateSnapshot,
        getChangedVmControlSnapshot,
        getCurrentFileBuffer,
        getCurrentFileMimeType,
        getCurrentFileName,
        getCurrentFilePreferenceId,
        getCurrentFileUrl,
        getCurrentCanvasSizing,
        getCurrentLayoutAlignment,
        getCurrentLayoutFit,
        getCurrentMcpPort,
        getCurrentRuntime,
        getEffectiveRuntimeVersionToken,
        getEventLogEntries,
        getEventLogFilterState,
        getLiveConfig,
        getLiveConfigState,
        getRiveInstance,
        getRuntimeAsset,
        getRuntimeSourceText,
        getRuntimeVersion,
        getRuntimeVersionToken,
        getSelectedControlKeys,
        getSidebarVisibility,
        getTauriEventListener,
        getTauriInvoker,
        getCanvasBackgroundStateSnapshot,
        getVmExplorerSnippetState,
        getVmSyncDiagnostics,
        getEditorCode,
        handleFileButtonClick,
        handleResize,
        hideError,
        initLucideIcons,
        injectCodeSnippet,
        isTauriEnvironment,
        loadRiveAnimation,
        logEvent,
        pause,
        play,
        refreshCurrentState,
        refreshInfoStrip,
        refreshVmInputControls,
        reset,
        resetArtboardSwitcherState,
        resetToDefaultArtboard,
        resetVmInputControls,
        restoreFileSessionUi,
        serializeControlHierarchy,
        serializeVmHierarchy,
        setCurrentFile,
        setCurrentCanvasSizing,
        setCurrentLayoutAlignment,
        setCurrentLayoutFit,
        setCurrentMcpPort,
        setCurrentRuntime,
        setEditorCode,
        setLiveConfigSource,
        setSidebarVisibility,
        setVmExplorerSnippetEnabled,
        showError,
        showMcpSetup,
        switchArtboard,
        switchVmInstance,
        toggleInstantiationControlsDialog,
        toggleLiveConfigSource,
        updateInfo,
        updateVersionInfo,
        scriptConsoleController,
    } = callbacks;

    const fileSessionController = createFileSessionController({
        callbacks: {
            applyStoredRuntimeVersionForCurrentFile,
            buildFileRuntimePreferenceId,
            cleanupInstance,
            ensureTauriBridge,
            getTauriEventListener,
            getTauriInvoker,
            hideError,
            initLucideIcons,
            isTauriEnvironment,
            loadRiveAnimation,
            logEvent,
            refreshInfoStrip,
            resetArtboardSwitcherState,
            resetVmInputControls,
            restoreFileSessionUi,
            showError,
        },
        elements,
    });

    let installCounterController = null;
    let defaultRivAppController = null;
    const shellController = createShellController({
        callbacks: {
            ensureRuntime,
            getCurrentFileName,
            getCurrentFileUrl,
            getCurrentCanvasSizing,
            getCurrentLayoutAlignment,
            getCurrentLayoutFit,
            getCurrentMcpPort,
            getCurrentRuntime,
            getEventLogFilterState,
            getRiveInstance,
            getTauriEventListener,
            getTauriInvoker,
            getInstallCounterStatus: () => installCounterController?.getStatusSnapshot?.() || null,
            getDefaultRivAppStatus: () => defaultRivAppController?.getStatusSnapshot?.() || null,
            handleResize,
            loadRiveAnimation,
            logEvent,
            isTauriEnvironment,
            reloadCurrentAnimation: refreshCurrentState,
            refreshInfoStrip,
            setCurrentCanvasSizing,
            setCurrentLayoutAlignment,
            setCurrentLayoutFit,
            setCurrentMcpPort,
            setCurrentRuntime,
            setInstallCounterEnabled: (enabled) => (
                installCounterController?.setEnabled?.(enabled) ?? Promise.resolve(false)
            ),
            makeRavDefaultForRiv: () => defaultRivAppController?.apply?.() ?? Promise.resolve(false),
            refreshDefaultRivAppStatus: () => defaultRivAppController?.refresh?.() ?? Promise.resolve(null),
            showError,
            updateInfo,
            updateVersionInfo,
        },
        elements,
    });

    const demoExportController = createDemoExportController({
        callbacks: {
            ensureRuntime,
            getTauriInvoker,
            logEvent,
            showError,
            updateInfo,
        },
        captureVmControlSnapshot,
        getArtboardStateSnapshot,
        getCurrentFileBuffer,
        getCurrentFileName,
        getCurrentFilePreferenceId,
        getCurrentCanvasSizing,
        getCurrentLayoutAlignment,
        getCurrentLayoutFit,
        getCurrentRuntime,
        getEditorConfig: getLiveConfig,
        getEffectiveRuntimeVersionToken,
        getLayoutStateSnapshot: () => shellController?.captureLayoutStateForExport() ?? {},
        getLiveConfigState,
        getRiveInstance,
        getRuntimeAsset,
        getRuntimeVersionToken,
        getSelectedControlKeys,
        getCanvasBackgroundStateSnapshot,
        getChangedVmControlSnapshot,
        serializeVmHierarchy,
    });

    const renderSurfaceController = createRenderSurfaceController({
        callbacks: {
            getControlSnapshot: captureVmControlSnapshot,
            getPresentationState: () => ({
                ...getCanvasBackgroundStateSnapshot(),
                canvasSizing: getCurrentCanvasSizing(),
                layoutAlignment: getCurrentLayoutAlignment(),
                layoutFit: getCurrentLayoutFit(),
            }),
            getTauriEventListener,
            getTauriInvoker,
            isTauriEnvironment,
            logEvent,
            showError,
            updateInfo,
        },
        demoExportController,
        elements,
    });

    installCounterController = createInstallCounterController({
        elements,
        getTauriInvoker,
        isTauriEnvironment,
        logEvent,
    });

    defaultRivAppController = createDefaultRivAppController({
        elements,
        getTauriInvoker,
        isTauriEnvironment,
        logEvent,
    });

    const instantiationControlsDialogController = createInstantiationControlsDialogController({
        callbacks: {
            closeUiOverlay: (options) => shellController.uiOverlayController.close(options),
            createDemoBundle: (options) => demoExportController.createDemoBundle(options),
            generateWebInstantiationCode: (options) => demoExportController.generateWebInstantiationCode(options),
            getCurrentFileName,
            getTauriInvoker,
            initLucideIcons,
            logEvent,
            requestUiOverlay: (request) => shellController.openUiOverlay(request),
            showError,
            updateInfo,
        },
        captureVmControlSnapshot,
        elements,
        getChangedVmControlSnapshot,
        serializeControlHierarchy,
    });

    const globalBindingsController = createGlobalBindingsController({
        callbacks: {
            applyCodeAndReload,
            createDemoBundle,
            ensureEditorReady,
            exportDemoToPath: (outputPath, options) => demoExportController.exportDemoToPath(outputPath, options),
            openIsolatedPlayback: (options) => demoExportController.openIsolatedPlayback(options),
            getArtboardStateSnapshot,
            getCanvasBackgroundStateSnapshot,
            getCurrentFileBuffer,
            getCurrentFileMimeType,
            getCurrentFileName,
            getCurrentRuntime,
            getEventLogEntries,
            getGenerateWebInstantiationCode: async (packageSource, snippetMode) => (
                demoExportController.generateWebInstantiationCode({ packageSource, snippetMode })
            ),
            getLiveConfigState,
            getRenderSurfaceState: () => renderSurfaceController.getState(),
            getRenderSurfaceController: () => renderSurfaceController,
            getRuntimeSourceText,
            getRuntimeVersion,
            getScriptConsoleEntries: (limit) => scriptConsoleController.readCaptured(limit),
            getSidebarVisibility,
            getCurrentCanvasSizing,
            getVmExplorerSnippetState,
            getVmSyncDiagnostics,
            handleFileButtonClick,
            injectCodeSnippet,
            loadRiveAnimation,
            logEvent,
            closeScriptConsole: () => {
                void consoleModeController.setConsoleOpen(false);
                return { open: false };
            },
            execScriptConsole: async (code) => {
                await consoleModeController.setConsoleMode('js');
                return scriptConsoleController.exec(code);
            },
            getEditorCode,
            isScriptConsoleOpen: () => scriptConsoleController.isOpen(),
            openScriptConsole: async () => {
                await consoleModeController.setConsoleMode('js');
                return { open: true };
            },
            setConsoleMode: async (mode) => consoleModeController.setConsoleMode(mode),
            setScriptConsoleFilter: (filter) => scriptConsoleController.setFilter(filter),
            setEventLogFilter: (filter) => eventLogController.setFilter(filter),
            clearScriptConsole: () => scriptConsoleController.clear(),
            clearEventLog: () => eventLogController.clearLog(),
            configureInstantiationControls: (options) => (
                instantiationControlsDialogController.configureForMcp(options)
            ),
            pause,
            play,
            refreshVmInputControls,
            reset,
            resetToDefaultArtboard,
            setCurrentFile,
            stageCurrentFile: (...args) => fileSessionController.stageCurrentFile(...args),
            setCurrentCanvasSizing,
            setCanvasSizingState: (nextState, message) => shellController?.applyCanvasSizingState?.(nextState, message),
            setRuntimeSelection: (runtime) => shellController.setRuntimeSelection(runtime),
            setEditorCode,
            setLiveConfigSource,
            setInstallCounterEnabled: (enabled) => installCounterController.setEnabled(enabled),
            setSidebarVisibility,
            setVmExplorerSnippetEnabled,
            showMcpSetup,
            switchArtboard,
            switchVmInstance,
            toggleInstantiationControlsDialog,
            toggleLiveConfigSource,
        },
        elements,
    });

    return {
        demoExportController,
        fileSessionController,
        globalBindingsController,
        instantiationControlsDialogController,
        installCounterController,
        defaultRivAppController,
        renderSurfaceController,
        shellController,
    };
}
