import { createPlatformStack } from './platform-stack.js';
import { createRiveStack } from './rive-stack.js';
import { createRuntimeStack } from './runtime-stack.js';
import { createUiStack } from './ui-stack.js';

export function createControllerStack({
    elements,
    placeholders,
    callbacks,
    refs,
    runtimeState,
} = {}) {
    const {
        codeMirrorModulesRef,
        getRefreshCurrentState,
        loadCodeMirror,
    } = refs;
    const {
        buildFileRuntimePreferenceId,
        cleanupInstance,
        createDemoBundle,
        ensureTauriBridge,
        getCurrentFileBuffer,
        getCurrentFileMimeType,
        getCurrentFileName,
        getCurrentFilePreferenceId,
        getCurrentFileSizeBytes,
        getCurrentFileUrl,
        getCurrentLayoutAlignment,
        getCurrentLayoutFit,
        getCurrentMcpPort,
        getCurrentRuntime,
        getRiveInstance,
        getRuntimeVersionToken,
        getTauriEventListener,
        getTauriInvoker,
        handleResize,
        hideError,
        initLucideIcons,
        isTauriEnvironment,
        loadRiveAnimation,
        normalizeOpenedFilePath,
        resolveAppVersion,
        setCurrentLayoutAlignment,
        setCurrentLayoutFit,
        setCurrentMcpPort,
        setCurrentRuntime,
        showError,
        updateInfo,
        updateVersionInfo,
    } = callbacks;
    let runtimeStack = null;

    const uiStack = createUiStack({
        elements,
        placeholders,
        callbacks: {
            getCurrentFileName,
            getCurrentFileSizeBytes,
            getCurrentRuntime,
            getCurrentRuntimeSource: () => runtimeStack?.getCurrentRuntimeSource?.(),
            getCurrentRuntimeVersion: () => runtimeStack?.getCurrentRuntimeVersion?.(),
            getLoadedRuntime: () => runtimeStack?.getLoadedRuntime?.(),
            getRuntimeVersionToken,
            getTauriEventListener,
            getTauriInvoker,
            handleResize,
            initLucideIcons,
            isTauriEnvironment,
            loadRiveAnimation,
            refreshCurrentState: (...args) => getRefreshCurrentState()(...args),
            resolveAppVersion,
            showError,
            updateInfo,
        },
        refs: {
            codeMirrorModulesRef,
            getCurrentFileUrl,
            loadCodeMirror,
        },
    });

    runtimeStack = createRuntimeStack({
        elements,
        state: runtimeState,
        callbacks: {
            getCurrentFileName,
            getCurrentFilePreferenceId,
            getCurrentFileUrl,
            getCurrentRuntime,
            getCurrentRuntimeVersionToken: getRuntimeVersionToken,
            getRiveInstance,
            getTauriInvoker,
            isTauriEnvironment,
            loadRiveAnimation,
            logEvent: uiStack.logEvent,
            refreshCurrentState: (...args) => getRefreshCurrentState()(...args),
            refreshInfoStrip: callbacks.refreshInfoStrip,
            showError,
            updateVersionInfo,
        },
    });
    const runtimeLoaderController = runtimeStack.runtimeLoaderController;
    const {
        applyRuntimeVersionToken,
        applyStoredRuntimeVersionForCurrentFile,
        ensureRuntime,
        getCurrentRuntimeSource,
        getCurrentRuntimeVersion,
        getEffectiveRuntimeVersionToken,
        getLoadedRuntime,
        getRuntimeAsset,
        getRuntimeSourceText,
        getRuntimeVersion,
        setupRuntimeVersionPicker,
    } = runtimeLoaderController;
    const transparencyController = runtimeStack.transparencyController;
    const {
        cleanupTransparencyRuntime,
        getStateSnapshot: getTransparencyStateSnapshot,
        isCanvasEffectivelyTransparent,
        setupCanvasColor,
        setupTransparencyControls,
        syncTransparencyControls,
    } = transparencyController;

    const riveStack = createRiveStack({
        elements,
        callbacks: {
            cleanupTransparencyRuntime,
            ensureRuntime,
            getCurrentFileBuffer,
            getCurrentFileName,
            getCurrentFileUrl,
            getCurrentLayoutAlignment,
            getCurrentLayoutFit,
            getCurrentRuntime,
            getLoadedRuntime,
            getLiveConfig: uiStack.getLiveConfig,
            getRiveInstance,
            hideError,
            initLucideIcons,
            isCanvasEffectivelyTransparent,
            loadRiveAnimation,
            logEvent: uiStack.logEvent,
            refreshInfoStrip: callbacks.refreshInfoStrip,
            showError,
            updateInfo,
        },
    });

    const platformStack = createPlatformStack({
        elements,
        callbacks: {
            applyCodeAndReload: uiStack.applyCodeAndReload,
            applyStoredRuntimeVersionForCurrentFile,
            buildFileRuntimePreferenceId: (fileName, fileSizeBytes, metadata = {}) => (
                buildFileRuntimePreferenceId(fileName, fileSizeBytes, metadata, normalizeOpenedFilePath)
            ),
            captureVmControlSnapshot: riveStack.captureVmControlSnapshot,
            cleanupInstance,
            consoleModeController: uiStack.consoleModeController,
            createDemoBundle,
            ensureEditorReady: uiStack.ensureEditorReady,
            ensureRuntime,
            ensureTauriBridge,
            getArtboardStateSnapshot: riveStack.getArtboardStateSnapshot,
            getChangedVmControlSnapshot: riveStack.getChangedVmControlSnapshot,
            getCurrentFileBuffer,
            getCurrentFileMimeType,
            getCurrentFileName,
            getCurrentFileUrl,
            getCurrentLayoutAlignment,
            getCurrentLayoutFit,
            getCurrentMcpPort,
            getCurrentRuntime,
            getEffectiveRuntimeVersionToken,
            getEditorCode: uiStack.getEditorCode,
            getEventLogEntries: uiStack.getEventLogEntries,
            getEventLogFilterState: uiStack.getEventLogFilterState,
            getLiveConfig: uiStack.getLiveConfig,
            getLiveConfigState: uiStack.getLiveConfigState,
            getRiveInstance,
            getRuntimeAsset,
            getRuntimeSourceText,
            getRuntimeVersion,
            getRuntimeVersionToken,
            getSelectedControlKeys: () => platformStack.instantiationControlsDialogController?.getSelectedControlKeys() ?? null,
            getSidebarVisibility: () => platformStack.shellController?.getSidebarVisibility?.() ?? { left: false, right: true },
            getTauriEventListener,
            getTauriInvoker,
            getTransparencyStateSnapshot,
            getVmExplorerSnippetState: uiStack.getVmExplorerSnippetState,
            handleFileButtonClick: () => platformStack.fileSessionController?.handleFileButtonClick(),
            handleResize,
            hideError,
            initLucideIcons,
            injectCodeSnippet: uiStack.injectCodeSnippet,
            isTauriEnvironment,
            loadRiveAnimation,
            logEvent: uiStack.logEvent,
            pause: riveStack.pause,
            play: riveStack.play,
            refreshCurrentState: (...args) => getRefreshCurrentState()(...args),
            refreshInfoStrip: callbacks.refreshInfoStrip,
            refreshVmInputControls: riveStack.renderVmInputControls,
            reset: riveStack.reset,
            resetArtboardSwitcherState: riveStack.resetArtboardSwitcherState,
            resetToDefaultArtboard: riveStack.resetToDefaultArtboard,
            resetVmInputControls: riveStack.resetVmInputControls,
            serializeControlHierarchy: riveStack.serializeControlHierarchy,
            serializeVmHierarchy: riveStack.serializeVmHierarchy,
            setCurrentFile: (...args) => platformStack.fileSessionController?.setCurrentFile(...args),
            setCurrentLayoutAlignment,
            setCurrentLayoutFit,
            setCurrentMcpPort,
            setCurrentRuntime,
            setEditorCode: uiStack.setEditorCode,
            setLiveConfigSource: uiStack.setLiveConfigSource,
            setSidebarVisibility: (visibility) => platformStack.shellController?.setSidebarVisibility?.(visibility) ?? { left: false, right: true },
            setVmExplorerSnippetEnabled: uiStack.setVmExplorerSnippetEnabled,
            showError,
            showMcpSetup: uiStack.showMcpSetup,
            switchArtboard: riveStack.switchArtboard,
            syncTransparencyControls,
            toggleInstantiationControlsDialog: (action) => platformStack.instantiationControlsDialogController?.toggleDialog(action),
            toggleLiveConfigSource: uiStack.toggleLiveConfigSource,
            updateInfo,
            updateVersionInfo,
            scriptConsoleController: uiStack.scriptConsoleController,
        },
    });

    uiStack.scriptConsoleController.installCapture();

    return {
        ...uiStack,
        ...riveStack,
        ...platformStack,
        applyRuntimeVersionToken,
        cleanupTransparencyRuntime,
        ensureRuntime,
        getCurrentRuntimeSource,
        getCurrentRuntimeVersion,
        getEffectiveRuntimeVersionToken,
        getLoadedRuntime,
        getRuntimeAsset,
        getRuntimeSourceText,
        getRuntimeVersion,
        getTransparencyStateSnapshot,
        isCanvasEffectivelyTransparent,
        setupCanvasColor,
        setupRuntimeVersionPicker,
        setupTransparencyControls,
        syncTransparencyControls,
    };
}
