import { createDemoExportController } from '../platform/demo-export.js';
import { createFileSessionController } from '../platform/file-session.js';
import { createGlobalBindingsController } from '../platform/global-bindings.js';
import { createShellController } from '../ui/shell-controller.js';
import { createInstantiationControlsDialogController } from '../ui/instantiation-controls-dialog.js';

export function createPlatformStack({
    elements,
    callbacks,
} = {}) {
    const {
        applyCodeAndReload,
        applyStoredRuntimeVersionForCurrentFile,
        buildFileRuntimePreferenceId,
        captureVmControlSnapshot,
        cleanupInstance,
        consoleModeController,
        createDemoBundle,
        ensureEditorReady,
        ensureRuntime,
        ensureTauriBridge,
        getArtboardStateSnapshot,
        getChangedVmControlSnapshot,
        getCurrentFileBuffer,
        getCurrentFileMimeType,
        getCurrentFileName,
        getCurrentFileUrl,
        getCurrentLayoutAlignment,
        getCurrentLayoutFit,
        getCurrentMcpPort,
        getCurrentRuntime,
        getEffectiveRuntimeVersionToken,
        getEventLogEntries,
        getEventLogFilterState,
        getLiveConfig,
        getLiveConfigState,
        getRiveInstance,
        getRuntimeAsset,
        getRuntimeSourceText,
        getRuntimeVersion,
        getRuntimeVersionToken,
        getSelectedControlKeys,
        getSidebarVisibility,
        getTauriEventListener,
        getTauriInvoker,
        getTransparencyStateSnapshot,
        getVmExplorerSnippetState,
        getEditorCode,
        handleFileButtonClick,
        handleResize,
        hideError,
        initLucideIcons,
        injectCodeSnippet,
        isTauriEnvironment,
        loadRiveAnimation,
        logEvent,
        pause,
        play,
        refreshCurrentState,
        refreshInfoStrip,
        refreshVmInputControls,
        reset,
        resetArtboardSwitcherState,
        resetToDefaultArtboard,
        resetVmInputControls,
        serializeControlHierarchy,
        serializeVmHierarchy,
        setCurrentFile,
        setCurrentLayoutAlignment,
        setCurrentLayoutFit,
        setCurrentMcpPort,
        setCurrentRuntime,
        setEditorCode,
        setLiveConfigSource,
        setSidebarVisibility,
        setVmExplorerSnippetEnabled,
        showError,
        showMcpSetup,
        switchArtboard,
        syncTransparencyControls,
        toggleInstantiationControlsDialog,
        toggleLiveConfigSource,
        updateInfo,
        updateVersionInfo,
        scriptConsoleController,
    } = callbacks;

    const fileSessionController = createFileSessionController({
        callbacks: {
            applyStoredRuntimeVersionForCurrentFile,
            buildFileRuntimePreferenceId,
            cleanupInstance,
            ensureTauriBridge,
            getTauriEventListener,
            getTauriInvoker,
            hideError,
            initLucideIcons,
            isTauriEnvironment,
            loadRiveAnimation,
            logEvent,
            refreshInfoStrip,
            resetArtboardSwitcherState,
            resetVmInputControls,
            showError,
        },
        elements,
    });

    const shellController = createShellController({
        callbacks: {
            ensureRuntime,
            getCurrentFileName,
            getCurrentFileUrl,
            getCurrentLayoutAlignment,
            getCurrentLayoutFit,
            getCurrentMcpPort,
            getCurrentRuntime,
            getEventLogFilterState,
            getTauriInvoker,
            getTransparencyStateSnapshot,
            handleResize,
            loadRiveAnimation,
            logEvent,
            reloadCurrentAnimation: refreshCurrentState,
            refreshInfoStrip,
            setCurrentLayoutAlignment,
            setCurrentLayoutFit,
            setCurrentMcpPort,
            setCurrentRuntime,
            showError,
            syncTransparencyControls,
            updateInfo,
            updateVersionInfo,
        },
        elements,
    });

    const demoExportController = createDemoExportController({
        callbacks: {
            ensureRuntime,
            getTauriInvoker,
            logEvent,
            showError,
            updateInfo,
        },
        captureVmControlSnapshot,
        getArtboardStateSnapshot,
        getCurrentFileBuffer,
        getCurrentFileName,
        getCurrentLayoutAlignment,
        getCurrentLayoutFit,
        getCurrentRuntime,
        getEditorConfig: getLiveConfig,
        getEffectiveRuntimeVersionToken,
        getLayoutStateSnapshot: () => shellController?.captureLayoutStateForExport() ?? {},
        getLiveConfigState,
        getRiveInstance,
        getRuntimeAsset,
        getRuntimeVersionToken,
        getSelectedControlKeys,
        getTransparencyStateSnapshot,
        getChangedVmControlSnapshot,
        serializeVmHierarchy,
    });

    const instantiationControlsDialogController = createInstantiationControlsDialogController({
        callbacks: {
            createDemoBundle: (options) => demoExportController.createDemoBundle(options),
            generateWebInstantiationCode: (options) => demoExportController.generateWebInstantiationCode(options),
            getCurrentFileName,
            getTauriInvoker,
            initLucideIcons,
            logEvent,
            showError,
            updateInfo,
        },
        captureVmControlSnapshot,
        elements,
        getChangedVmControlSnapshot,
        serializeControlHierarchy,
    });

    const globalBindingsController = createGlobalBindingsController({
        callbacks: {
            applyCodeAndReload,
            createDemoBundle,
            ensureEditorReady,
            exportDemoToPath: (outputPath) => demoExportController.exportDemoToPath(outputPath),
            getArtboardStateSnapshot,
            getCurrentFileBuffer,
            getCurrentFileMimeType,
            getCurrentFileName,
            getCurrentRuntime,
            getEventLogEntries,
            getGenerateWebInstantiationCode: async (packageSource, snippetMode) => (
                demoExportController.generateWebInstantiationCode({ packageSource, snippetMode })
            ),
            getLiveConfigState,
            getRuntimeSourceText,
            getRuntimeVersion,
            getScriptConsoleEntries: (limit) => scriptConsoleController.readCaptured(limit),
            getSidebarVisibility,
            getVmExplorerSnippetState,
            handleFileButtonClick,
            injectCodeSnippet,
            loadRiveAnimation,
            logEvent,
            closeScriptConsole: () => {
                void consoleModeController.setConsoleMode('events');
                return { open: false };
            },
            execScriptConsole: async (code) => {
                await consoleModeController.setConsoleMode('js');
                return scriptConsoleController.exec(code);
            },
            getEditorCode,
            isScriptConsoleOpen: () => scriptConsoleController.isOpen(),
            openScriptConsole: async () => {
                await consoleModeController.setConsoleMode('js');
                return { open: true };
            },
            pause,
            play,
            refreshVmInputControls,
            reset,
            resetToDefaultArtboard,
            setCurrentFile,
            setEditorCode,
            setLiveConfigSource,
            setSidebarVisibility,
            setVmExplorerSnippetEnabled,
            showMcpSetup,
            switchArtboard,
            toggleInstantiationControlsDialog,
            toggleLiveConfigSource,
        },
        elements,
    });

    return {
        demoExportController,
        fileSessionController,
        globalBindingsController,
        instantiationControlsDialogController,
        shellController,
    };
}
